name: Verify Flaky Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  verify-flaky-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Build project (skip tests)
      run: mvn clean install -DskipTests

    - name: Run normal test
      run: mvn -Dtest=org.jbpm.casemgmt.impl.CaseServiceImplTest#testStartExpressionCaseWithCaseFile test

    - name: Install NonDex
      run: |
        git clone https://github.com/TestingResearchIllinois/NonDex.git
        cd NonDex
        mvn clean install -DskipTests

    - name: Run NonDex test
      run: |
        ~/.m2/repository/edu/illinois/nondex/nondex-maven-plugin/2.1.1/nondex-maven-plugin-2.1.1.jar
        mvn edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=org.jbpm.casemgmt.impl.CaseServiceImplTest#testStartExpressionCaseWithCaseFile
