name: Flaky Test Verification

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  verify-flaky-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout IDoFT repository
        uses: actions/checkout@v3
        
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Checkout DataflowTemplates repository
        uses: actions/checkout@v3
        with:
          repository: GoogleCloudPlatform/DataflowTemplates
          path: DataflowTemplates
          ref: 5094c7b39de511c9ed441d9fde28553a88f68e4b
          
      - name: Build DataflowTemplates
        working-directory: ./DataflowTemplates
        run: mvn clean install -DskipTests
        
      - name: Run test normally (should pass)
        working-directory: ./DataflowTemplates
        run: |
          echo "Running test without NonDex - should PASS"
          mvn test -Dtest=com.google.cloud.teleport.bigtable.CassandraRowMapperFnTest#testListColumn
          echo "Test passed without NonDex as expected"
        
      - name: Run test with NonDex (should fail)
        working-directory: ./DataflowTemplates
        continue-on-error: true
        id: nondex-run
        run: |
          echo "Running test with NonDex - should FAIL"
          mvn edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=com.google.cloud.teleport.bigtable.CassandraRowMapperFnTest#testListColumn
          exit_code=$?
          if [ $exit_code -eq 0 ]; then
            echo "Test unexpectedly passed with NonDex"
            exit 1
          else
            echo "Test failed with NonDex as expected"
          fi
          
      - name: Check NonDex results
        working-directory: ./DataflowTemplates
        run: |
          echo "Checking NonDex results directory"
          ls -la .nondex/
          for dir in .nondex/*/; do
            echo "Contents of $dir:"
            ls -la "$dir"
            if [ -f "$dir/failure" ]; then
              echo "Found failure file in $dir:"
              cat "$dir/failure"
            fi
          done